/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProjectButton: typeof import('./src/components/add-project-button.vue')['default']
    AddStepModal: typeof import('./src/components/add-step-modal.vue')['default']
    AppAboutButton: typeof import('./src/components/app-about-button.vue')['default']
    AppActions: typeof import('./src/components/app-actions.vue')['default']
    AppDebug: typeof import('./src/components/app-debug.vue')['default']
    AppFooter: typeof import('./src/components/app-footer.vue')['default']
    AppLoginButton: typeof import('./src/components/app-login-button.vue')['default']
    AppNavbar: typeof import('./src/components/app-navbar.vue')['default']
    AppProject: typeof import('./src/components/app-project.vue')['default']
    AppProjects: typeof import('./src/components/app-projects.vue')['default']
    AppStep: typeof import('./src/components/app-step.vue')['default']
    AppToast: typeof import('./src/components/app-toast.vue')['default']
    DeleteProjectModal: typeof import('./src/components/delete-project-modal.vue')['default']
    DeleteStepModal: typeof import('./src/components/delete-step-modal.vue')['default']
    IconGithub: typeof import('./src/components/icon-github.vue')['default']
    ToggleEditButton: typeof import('./src/components/toggle-edit-button.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDialog: typeof import('vuetify/components')['VDialog']
    VFooter: typeof import('vuetify/components')['VFooter']
    VForm: typeof import('vuetify/components')['VForm']
    VIcon: typeof import('vuetify/components')['VIcon']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VMenu: typeof import('vuetify/components')['VMenu']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VRow: typeof import('vuetify/components')['VRow']
    VSnackbar: typeof import('vuetify/components')['VSnackbar']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VTextField: typeof import('vuetify/components')['VTextField']
  }
}
